linux_ssh_improvment AX-2943 (#2471)
* fix hostname bug

* always check for errors

* add devops.rc

* add executor, removed names, add concat commands

* refactor client_id

* make get_commands protected

* fix concat commands, add test for os build

* better tests, fix version parsing

* fix recursive concat command, add tests

* support for old version of df

* add rpm, fix parse function report success on empty data

* fix rpm command, and fix raw data

* add support for empty password

* sudo support, minor bugfix in concat commands, empty password support, try except for to_axonius iters

* remove parallel tests

* add hardware parsing

* Revert "remove parallel tests"

This reverts commit a19cacef83477d223c2682aa84f0bd2f9d5d3fdd.

* re-added REQUIRE_ROOT

* add cpu manufacturer, add auto property detection

* print verbose assert message

For example
AssertionError: linux_ssh_06:A1:4A:D6:AF:4A_10.0.2.26:22_ip-10-0-2-26 not in
    ['linux_ssh_\ncentos-6-yitai-schwartz\n_10.20.0.9:22_42:01:0A:14:00:09',
     'linux_ssh_\ncentos-7-yitai-schwartz\n_10.20.0.8:22_42:01:0A:14:00:08',
     'linux_ssh_\nip-10-0-2-26\n_06:A1:4A:D6:AF:4A_10.0.2.26:22',
     'linux_ssh_\nredhat-6-yitai-schwartz\n_10.20.0.7:22_42:01:0A:14:00:07',
     'linux_ssh_\nredhat-7-yitai-schwartz\n_10.20.0.4:22_42:01:0A:14:00:04']

* better print on failure

* fix hostname and magic handling

* fix hardwarae tests

* don't fail on notype motherboard

* strip before split

* Fix grammer mistake, remove unused import

* clearer description for sudoer

* move default to client connect