Bug/AX-616 support for json complex data types (datetime) in 'devices' and 'devices_by_name' (#552)
* auto set datetime as datetime string format
fixed bool issue

* FIXED support for complex data types (like data-time) to json in 'devices' and 'devices_by_name' and adjusted their usages (container communication)

* fixed <generator object LdapConnection.get_device_list at 0x7feeb02b1678> is not JSON serializable

Traceback (most recent call last):
  File "/home/axonius/libs/axonius-py/axonius/plugin_base.py", line 116, in actual_wrapper
    return func(self, *args, **kwargs)
  File "/home/axonius/libs/axonius-py/axonius/adapter_base.py", line 138, in devices
    return json.dumps(dict(self._query_devices()), default=json_util.default)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/bson/json_util.py", line 852, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: <generator object LdapConnection.get_device_list at 0x7feeb02b1678> is not JSON serializable

* fixed datetime<->json OverflowError: date value out of range

* typos

* added full support for generators

* removed unused imports

* added support for dict_values (and the rest of his friends)

* fixed typo