Fix excluded adapters force dict if none (#6779)
* another test fix

* blat

* wrong branch buddy

* BUGFIX for gui_helpers:parse_entity_fields()

Found in 3.8.2 RC4!!!!

It is referencing excluded_adapters a dictionary but excluded_adapters defaults to None, which
causes public API calls to get assets with include_details=True to throw the following exception:

31/08/20 15:48:12:724000  ERROR    UUID 10d728e1-873a-454e-b7dc-0664b5b11cb6: error traceback: Traceback (most recent call last):
  File /home/axonius/libs/axonius-py/axonius/plugin_base.py, line 280, in actual_wrapper
  File ./gui/api.py, line 1196, in api_devices_cursor
  File ./gui/api.py, line 925, in api_get_assets_cursor
  File ./gui/api.py, line 925, in <listcomp>
  File /home/axonius/libs/axonius-py/axonius/utils/db_querying_helper.py, line 281, in convert_entities_to_frontend_entities
  File /home/axonius/libs/axonius-py/axonius/utils/gui_helpers.py, line 925, in parse_entity_fields
  File /home/axonius/libs/axonius-py/axonius/utils/gui_helpers.py, line 927, in <dictcomp>
<class 'AttributeError'>:'NoneType' object has no attribute 'get'

Co-authored-by: ofrishur <31949107+ofrishur@users.noreply.github.com>